name: harmonization

channels:
    - conda-forge
    - pnlbwh
    - defaults
    - anaconda
    - aramislab

dependencies:
    - python>=3.6
    - ants
    - ipython
    - numpy
    - pandas
    - scipy
    - scikit-image
    - plumbum
    - conda-build
    - git
    - s3fs
    - pip
    - pip:
        - nibabel
        - dipy
        - psutil
        - git+https://github.com/mhe/pynrrd.git
        - git+https://github.com/pnlbwh/conversion.git
